name: Docker CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Pull Source Code
      uses: actions/checkout@v3

    # ขั้นตอนใหม่: ให้หุ่นยนต์ล็อกอินเข้าโกดัง
    - name: Step 2 - Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ขั้นตอนใหม่: สร้าง Image และดันขึ้นโกดังทันที
    - name: Step 3 - Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/nipa-portfolio-app:latest
